"""
Guards against Settings -> About's version drifting from pyproject.toml again.

APP_VERSION (src/version_utils.py) is read from installed package metadata
(importlib.metadata), which only reflects pyproject.toml after an editable
install refreshes it. These tests pin the two places that must stay in sync
so a future edit can't silently drop the refresh step or re-track the
generated metadata directory.

A second group of tests audits the declared dependency set against what is
actually imported, so a dependency nothing uses (as `keyring` was) cannot sit
in pyproject.toml unnoticed.
"""

import ast
import importlib.metadata
import re
import shutil
import subprocess
import tomllib
from collections.abc import Callable
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_GIT = shutil.which("git")
_RELEASE_SCRIPT = _REPO_ROOT / "scripts" / "release.ps1"


def test_release_script_refreshes_editable_install_metadata() -> None:
    # release.ps1 is gitignored (scripts/* -- it's a personal convenience script,
    # never committed), so it won't exist on a fresh clone or CI runner.
    if not _RELEASE_SCRIPT.exists():
        pytest.skip("scripts/release.ps1 is a local, gitignored file")
    content = _RELEASE_SCRIPT.read_text(encoding="utf-8")
    version_stamp_index = content.index("uv version $Version")
    install_index = content.index("uv pip install -e .")
    assert install_index > version_stamp_index, (
        "release.ps1 must run `uv pip install -e .` after stamping the version, "
        "so importlib.metadata.version('meadowlark') picks up the new version "
        "(mirrors the 'Install package in editable mode' step in "
        ".github/workflows/release.yml)."
    )


def test_egg_info_is_gitignored_and_not_tracked() -> None:
    gitignore = (_REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "*.egg-info/" in gitignore, (
        "*.egg-info/ must stay gitignored -- a committed copy freezes "
        "Settings -> About's version at whatever it read when committed."
    )
    assert _GIT is not None, "git must be on PATH to run this test"
    tracked = subprocess.run(  # noqa: S603 -- fixed argv, no shell, trusted git binary
        [_GIT, "ls-files", "meadowlark.egg-info"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    assert tracked == "", (
        "meadowlark.egg-info must not be committed -- it is regenerated by "
        "`uv pip install -e .` and a stale committed copy overrides the real "
        "version whenever this repo is on sys.path (see release.ps1)."
    )


_SOURCE_SUFFIXES = (".py", ".pyw")

# Declared runtime dependencies that are legitimately never `import`ed by this
# codebase. Every entry must say why it still has to ship -- an unjustified
# entry is exactly how `keyring` survived here unimported for months.
_NOT_DIRECTLY_IMPORTED: dict[str, str] = {
    "deno": (
        "Ships the deno.exe binary that meadowlark.spec bundles from "
        ".venv/Scripts; invoked as a subprocess, never imported."
    ),
    "yt-dlp-ejs": (
        "yt-dlp's JS-challenge solver; discovered and loaded by yt-dlp at "
        "runtime, not by this codebase."
    ),
    "bgutil-ytdlp-pot-provider": (
        "yt-dlp PO-token plugin in the `yt_dlp_plugins` namespace; yt-dlp "
        "discovers and loads it at runtime, meadowlark.spec lists its modules as "
        "hiddenimports, and src/pot_provider.py only probes it via find_spec()."
    ),
}

# Top-level directories whose sources never reach the frozen build, so their
# imports cannot justify a runtime dependency.
_NON_SHIPPED_DIRS = frozenset({"tests", "scripts"})


def _normalize(name: str) -> str:
    """PEP 503: lowercase, and collapse runs of - _ . into a single hyphen."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _dependency_name(requirement: str) -> str:
    """
    Extract and normalize the distribution name from a PEP 508 requirement.

    Strips extras, version specifiers and environment markers:
    "yt-dlp[default]>=2025.7.21 ; sys_platform == 'win32'" -> "yt-dlp"
    """
    return _normalize(re.split(r"[\[<>=!~;\s]", requirement, maxsplit=1)[0])


def _declared_dependencies() -> frozenset[str]:
    with (_REPO_ROOT / "pyproject.toml").open("rb") as handle:
        pyproject = tomllib.load(handle)
    return frozenset(
        _dependency_name(requirement) for requirement in pyproject["project"]["dependencies"]
    )


def _shipped_source_files() -> list[Path]:
    """Tracked Python sources outside _NON_SHIPPED_DIRS."""
    assert _GIT is not None, "git must be on PATH to run this test"
    tracked = subprocess.run(  # noqa: S603 -- fixed argv, no shell, trusted git binary
        [_GIT, "ls-files", "-z"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [
        _REPO_ROOT / relative
        for relative in tracked.split("\0")
        if relative.endswith(_SOURCE_SUFFIXES)
        and relative.split("/", 1)[0] not in _NON_SHIPPED_DIRS
    ]


def _top_level_imports(paths: list[Path]) -> frozenset[str]:
    """Every top-level module name imported anywhere in the given sources."""
    names: set[str] = set()
    for path in paths:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names.update(alias.name.split(".")[0] for alias in node.names)
            # node.level > 0 is a relative import -- no distribution behind it.
            elif isinstance(node, ast.ImportFrom) and not node.level and node.module:
                names.add(node.module.split(".")[0])
    return frozenset(names)


@pytest.fixture(scope="module")
def declared_deps() -> frozenset[str]:
    return _declared_dependencies()


@pytest.fixture(scope="module")
def imported_dists() -> frozenset[str]:
    """Distributions that actually back the imports in shipped source files."""
    provided = importlib.metadata.packages_distributions()
    return frozenset(
        _normalize(distribution)
        for name in _top_level_imports(_shipped_source_files())
        for distribution in provided.get(name, ())
    )


def _unexplained_dependencies(
    declared: frozenset[str],
    imported: frozenset[str],
    allowlist: dict[str, str],
) -> frozenset[str]:
    """Return declared dependencies that are neither imported nor allowlisted."""
    return declared - imported - allowlist.keys()


def _stale_allowlist_entries(
    declared: frozenset[str],
    allowlist: dict[str, str],
) -> frozenset[str]:
    """Allowlist entries that no longer correspond to a declared dependency."""
    return allowlist.keys() - declared


def _reintroduced_allowlist_entries(
    imported: frozenset[str],
    allowlist: dict[str, str],
) -> frozenset[str]:
    """Allowlist entries that are now directly imported after all."""
    return allowlist.keys() & imported


def test_dependency_audit_is_not_vacuous(imported_dists) -> None:
    # If the environment is unsynced, packages_distributions() resolves almost
    # nothing and the audit below would pass or fail for the wrong reason. Fail
    # loudly here instead, with the fix in the message.
    assert "pyqt6" in imported_dists, (
        "PyQt6 did not resolve through importlib.metadata, so this audit cannot "
        "see what is installed. Run `uv sync --group dev` and re-run; an "
        "unsynced environment makes the dependency audit meaningless."
    )


def test_every_declared_dependency_is_imported_or_justified(
    declared_deps,
    imported_dists,
) -> None:
    unexplained = _unexplained_dependencies(
        declared_deps,
        imported_dists,
        _NOT_DIRECTLY_IMPORTED,
    )
    assert not unexplained, (
        f"{sorted(unexplained)} are declared in pyproject.toml [project] "
        "dependencies but are never imported by any tracked source file. "
        "Either drop them -- as `keyring` was, which also shed pywin32-ctypes "
        "and the jaraco.* chain -- or add each to _NOT_DIRECTLY_IMPORTED with "
        "the reason it still has to ship."
    )


def test_not_directly_imported_allowlist_has_no_stale_entries(
    declared_deps,
    imported_dists,
) -> None:
    undeclared = _stale_allowlist_entries(declared_deps, _NOT_DIRECTLY_IMPORTED)
    assert not undeclared, (
        f"{sorted(undeclared)} are allowlisted in _NOT_DIRECTLY_IMPORTED but no "
        "longer declared in pyproject.toml -- delete those entries."
    )
    now_imported = _reintroduced_allowlist_entries(
        imported_dists,
        _NOT_DIRECTLY_IMPORTED,
    )
    assert not now_imported, (
        f"{sorted(now_imported)} are now imported directly -- remove them from "
        "_NOT_DIRECTLY_IMPORTED so the audit tracks them normally."
    )


def test_test_tooling_cannot_justify_a_runtime_dependency(imported_dists) -> None:
    # pytest-cov sat in [project] dependencies (and so in the frozen build's
    # dependency closure) because the audit counted tests/ imports as runtime
    # use. Only code that ships may vouch for a runtime dependency.
    assert "pytest" not in imported_dists, (
        "The runtime-dependency audit resolved `pytest` as imported, so it is "
        "scanning test code -- a test-only package could then sit in [project] "
        "dependencies unflagged."
    )


def test_keyring_is_not_reintroduced() -> None:
    for relative in ("pyproject.toml", "meadowlark.spec", "meadowlark.pyw"):
        text = (_REPO_ROOT / relative).read_text(encoding="utf-8")
        assert "keyring" not in text.lower(), (
            f"{relative} re-introduces keyring. Nothing in this codebase imports "
            "it; it was removed as dead weight along with pywin32-ctypes and the "
            "jaraco.* chain. If a real credential feature is being added, delete "
            "this test in the same commit as the first `import keyring`."
        )


# ---------------------------------------------------------------------------
# Boundary coverage for the pure helpers above. These exercise `_normalize`,
# `_dependency_name` and `_top_level_imports` directly against crafted input
# rather than only indirectly through the live pyproject.toml / tracked
# sources, and prove the two audit tests' failure paths actually fire.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("", ""),
        ("a", "a"),
        ("ab", "ab"),
        ("PyYAML", "pyyaml"),
        ("requests_oauthlib", "requests-oauthlib"),
        ("foo--bar", "foo-bar"),
        ("foo___bar", "foo-bar"),
        ("foo..bar", "foo-bar"),
        ("foo-_.bar", "foo-bar"),
        ("-foo", "-foo"),
        ("foo-", "foo-"),
        ("foo-bar", "foo-bar"),
        ("FOO", "foo"),
        ("2to3", "2to3"),
        ("café", "café"),
    ],
    ids=[
        "empty",
        "single-char",
        "two-chars",
        "mixed-case",
        "single-underscore",
        "double-hyphen",
        "triple-underscore",
        "double-dot",
        "mixed-separator-run",
        "leading-hyphen",
        "trailing-hyphen",
        "already-normalized-idempotent",
        "all-uppercase",
        "leading-digit",
        "unicode-accented",
    ],
)
def test_normalize_boundary_values(raw: str, expected: str) -> None:
    assert _normalize(raw) == expected


@pytest.mark.parametrize(
    ("requirement", "expected"),
    [
        ("requests", "requests"),
        ("yt-dlp[default]", "yt-dlp"),
        ("package>=1.0", "package"),
        ("package==1.0.0", "package"),
        ("package~=1.0", "package"),
        ("package!=1.0", "package"),
        ("package<=2.0", "package"),
        ("package<2.0", "package"),
        ("package>2.0", "package"),
        ("package; sys_platform == 'win32'", "package"),
        ("package ; extra == 'foo'", "package"),
        (
            "yt-dlp[default]>=2025.7.21 ; sys_platform == 'win32'",
            "yt-dlp",
        ),
        ("Some_Package.Name>=1.0", "some-package-name"),
        ("package [extra]", "package"),
        ("", ""),
    ],
    ids=[
        "bare-name",
        "extras-only",
        "specifier-gte",
        "specifier-eq",
        "specifier-compatible",
        "specifier-ne",
        "specifier-lte",
        "specifier-lt",
        "specifier-gt",
        "marker-no-space",
        "marker-with-space",
        "extras-specifier-marker-combo",
        "name-needs-normalization",
        "space-before-extras",
        "empty-requirement",
    ],
)
def test_dependency_name_boundary_values(requirement: str, expected: str) -> None:
    assert _dependency_name(requirement) == expected


def _write_source(tmp_path: Path, name: str, content: str) -> Path:
    path = tmp_path / name
    path.write_text(content, encoding="utf-8")
    return path


def test_top_level_imports_empty_file_yields_empty_set(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "empty.py", "")
    assert _top_level_imports([path]) == frozenset()


def test_top_level_imports_plain_import(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "plain.py", "import os\n")
    assert _top_level_imports([path]) == frozenset({"os"})


def test_top_level_imports_dotted_import_takes_first_segment(
    tmp_path: Path,
) -> None:
    path = _write_source(tmp_path, "dotted.py", "import os.path\n")
    assert _top_level_imports([path]) == frozenset({"os"})


def test_top_level_imports_comma_separated_import(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "multi.py", "import os, sys\n")
    assert _top_level_imports([path]) == frozenset({"os", "sys"})


def test_top_level_imports_from_import(tmp_path: Path) -> None:
    path = _write_source(
        tmp_path,
        "from_import.py",
        "from collections import OrderedDict\n",
    )
    assert _top_level_imports([path]) == frozenset({"collections"})


def test_top_level_imports_from_import_dotted_module(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "from_dotted.py", "from os.path import join\n")
    assert _top_level_imports([path]) == frozenset({"os"})


def test_top_level_imports_aliased_import(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "aliased.py", "import numpy as np\n")
    assert _top_level_imports([path]) == frozenset({"numpy"})


def test_top_level_imports_excludes_relative_imports(tmp_path: Path) -> None:
    path = _write_source(
        tmp_path,
        "relative.py",
        "from . import foo\nfrom .utils import bar\n",
    )
    assert _top_level_imports([path]) == frozenset()


def test_top_level_imports_descends_into_function_body(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "nested_func.py", "def f() -> None:\n    import json\n")
    assert _top_level_imports([path]) == frozenset({"json"})


def test_top_level_imports_descends_into_try_except(tmp_path: Path) -> None:
    content = "try:\n    import tomllib\nexcept ImportError:\n    import tomli as tomllib\n"
    path = _write_source(tmp_path, "try_except.py", content)
    assert _top_level_imports([path]) == frozenset({"tomllib", "tomli"})


def test_top_level_imports_descends_into_if_block(tmp_path: Path) -> None:
    path = _write_source(tmp_path, "if_block.py", "if True:\n    import sys\n")
    assert _top_level_imports([path]) == frozenset({"sys"})


def test_top_level_imports_unions_across_multiple_files(tmp_path: Path) -> None:
    first = _write_source(tmp_path, "first.py", "import os\n")
    second = _write_source(tmp_path, "second.py", "import sys\n")
    assert _top_level_imports([first, second]) == frozenset({"os", "sys"})


def _fake_git_ls_files(
    *relative_paths: str,
) -> Callable[..., subprocess.CompletedProcess[str]]:
    """Build a subprocess.run stub mimicking `git ls-files -z` output."""
    stdout = "".join(f"{path}\0" for path in relative_paths)

    def _run(*args: object, **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(args=args, returncode=0, stdout=stdout, stderr="")

    return _run


@pytest.mark.parametrize(
    ("relative_path", "should_be_shipped"),
    [
        ("src/qux.py", True),
        ("meadowlark.pyw", True),
        ("tests/foo.py", False),
        ("tests/sub/bar.py", False),
        ("scripts/baz.py", False),
        ("testsuite/module.py", True),
        ("scripts_extra/module.py", True),
        ("tests.py", True),
    ],
    ids=[
        "root-level-src-file",
        "root-level-pyw-file",
        "nested-under-tests-dir",
        "deeply-nested-under-tests-dir",
        "nested-under-scripts-dir",
        "sibling-dir-not-excluded-by-prefix",
        "sibling-dir-not-excluded-by-prefix-scripts",
        "root-file-named-like-excluded-dir",
    ],
)
def test_shipped_source_files_filters_by_exact_top_level_segment(
    monkeypatch: pytest.MonkeyPatch,
    relative_path: str,
    should_be_shipped: bool,
) -> None:
    # _shipped_source_files must exclude only an exact "tests"/"scripts" first
    # path segment, not any directory that merely starts with those names
    # (e.g. testsuite/), and must not treat a root-level file that shares a
    # name with an excluded directory (tests.py) as excluded.
    monkeypatch.setattr(subprocess, "run", _fake_git_ls_files(relative_path))
    shipped = {path.relative_to(_REPO_ROOT).as_posix() for path in _shipped_source_files()}
    assert (relative_path in shipped) is should_be_shipped


def test_dependency_audit_flags_undeclared_unimported_dependency() -> None:
    """
    Regression for the exact failure `keyring` should have tripped.

    A dependency present in `declared` but neither imported nor allowlisted
    must be reported by `_unexplained_dependencies`, proving the audit's
    failing path actually fires rather than only ever passing.
    """
    declared = frozenset({"keyring", "pyqt6"})
    imported = frozenset({"pyqt6"})
    unexplained = _unexplained_dependencies(declared, imported, _NOT_DIRECTLY_IMPORTED)
    assert unexplained == frozenset({"keyring"})


def test_dependency_audit_passes_when_allowlisted() -> None:
    """A declared-but-unimported dependency that IS allowlisted is not flagged."""
    declared = frozenset({"deno", "pyqt6"})
    imported = frozenset({"pyqt6"})
    unexplained = _unexplained_dependencies(declared, imported, _NOT_DIRECTLY_IMPORTED)
    assert unexplained == frozenset()


def test_allowlist_audit_flags_entry_no_longer_declared() -> None:
    """
    Regression: an allowlist key that drifts away from pyproject.toml.

    Simulates dropping a dependency from pyproject.toml (or a typo mutating
    the allowlist key) without removing the now-stale `_NOT_DIRECTLY_IMPORTED`
    entry -- `_stale_allowlist_entries` must catch it.
    """
    declared = frozenset({"pyqt6"})
    mutated_allowlist = {"mutated-key-not-declared": "stale reason"}
    stale = _stale_allowlist_entries(declared, mutated_allowlist)
    assert stale == frozenset({"mutated-key-not-declared"})


def test_allowlist_audit_flags_entry_now_imported() -> None:
    """
    Regression: an allowlisted dependency that starts being imported.

    Once code imports what the allowlist claims is never imported, the entry
    is stale in the other direction -- `_reintroduced_allowlist_entries` must
    catch it so the allowlist gets trimmed instead of masking real usage.
    """
    imported = frozenset({"deno", "pyqt6"})
    allowlist = {"deno": "no longer accurate once this fires"}
    now_imported = _reintroduced_allowlist_entries(imported, allowlist)
    assert now_imported == frozenset({"deno"})
